// app
export const APP_WRITE_USER_DATA = 'APP_WRITE_USER_DATA';
export const APP_IS_NOT_AUTH = 'APP_IS_NOT_AUTH';
export const APP_WRITE_TABLE_DATA = 'APP_WRITE_TABLE_DATA';
export const APP_SET_UNSUB_DATA = 'APP_SET_UNSUB_DATA';
export const APP_TRACK_UNSUB = 'APP_TRACK_UNSUB';

// members
export const MEMBERS_WRITE_MEMBER_DATA = 'MEMBERS_WRITE_MEMBER_DATA';
export const MEMBERS_CLEAR_MEMBER_DATA = 'MEMBERS_CLEAR_MEMBER_DATA';
export const MEMBERS_IS_READ_ONLY = 'MEMBERS_IS_READ_ONLY';

// tasks
export const TASKS_WRITE_MEMBER_DATA = 'TASKS_WRITE_MEMBER_DATA';
export const TASKS_CLEAR_MEMBER_DATA = 'TASKS_CLEAR_MEMBER_DATA';
export const TASKS_IS_READ_ONLY = 'TASKS_IS_READ_ONLY';

// memberPropgress
export const PROGRESS_WRITE_MEMBER_DATA = 'PROGRESS_WRITE_MEMBER_DATA';
export const PROGRESS_WRITE_PROGRESS_DATA = 'PROGRESS_WRITE_PROGRESS_DATA';

// memberTasks
export const MEMBER_TASKS_WRITE_MEMBER_DATA = 'MEMBER_TASKS_WRITE_MEMBER_DATA';
export const MEMBER_TASKS_WRITE_TASKS_DATA = 'MEMBER_TASKS_WRITE_TASKS_DATA';
export const MEMBER_TASKS_SHOW_FORM = 'MEMBER_TASKS_SHOW_FORM';
export const MEMBER_TASKS_SET_TASK_DATA = 'MEMBER_TASKS_SET_TASK_DATA';
export const PROGRESS_CLEAR_MEMBER_DATA = 'PROGRESS_CLEAR_MEMBER_DATA';

// taskTrack
export const TASK_TRACK_SET_SUBTASKS_DATA = 'TASK_TRACK_SET_SUBTASKS_DATA';
export const TASK_TRACK_SET_SUBTASK_DATA = 'TASK_TRACK_SET_SUBTASK_DATA';
export const TASK_TRACK_SET_UNSUB_DATA = 'TASK_TRACK_SET_UNSUB_DATA';
export const TASK_TRACK_SET_DATA_LOAD = 'TASK_TRACK_SET_DATA_LOAD';
export const TASK_TRACK_FORM_SHOW = 'TASK_TRACK_FORM_SHOW';
export const TASK_TRACK_CLEAR_MEMBER_DATA = 'TASK_TRACK_CLEAR_MEMBER_DATA';
export const TASK_TRACK_SET_DETAIL_MODE = 'TASK_TRACK_SET_DETAIL_MODE';
export const TASK_TRACK_UNSUB = 'TASK_TRACK_UNSUB';

// memberForm
export const MEMBER_FORM_SET_MEMBER_DATA = 'MEMBER_FORM_SET_MEMBER_DATA';
export const MEMBER_FORM_SET_USER_ID = 'MEMBER_FORM_SET_USER_ID';
export const MEMBER_FORM_SET_INPUT_CHANGE = 'MEMBER_FORM_SET_INPUT_CHANGE';
